/*
 * User Details API Task
 * This is an API providing details about users along with languages and frameworks.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: sanketdeotale@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
