/*
 * User Details API Task
 * This is an API providing details about users along with languages and frameworks.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: sanketdeotale@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Containing user info
 */
@Schema(description = "Containing user info")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-28T20:06:30.550174248Z[GMT]")
public class User {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("user name")
  private String userName = null;

  @SerializedName("user id")
  private String userId = null;

  @SerializedName("user language")
  private String userLanguage = null;

  @SerializedName("user framework")
  private String userFramework = null;

  public User id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "4", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public User userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(example = "Sanket", description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public User userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(example = "1234", description = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public User userLanguage(String userLanguage) {
    this.userLanguage = userLanguage;
    return this;
  }

   /**
   * Get userLanguage
   * @return userLanguage
  **/
  @Schema(example = "Java", description = "")
  public String getUserLanguage() {
    return userLanguage;
  }

  public void setUserLanguage(String userLanguage) {
    this.userLanguage = userLanguage;
  }

  public User userFramework(String userFramework) {
    this.userFramework = userFramework;
    return this;
  }

   /**
   * Get userFramework
   * @return userFramework
  **/
  @Schema(example = "Spring", description = "")
  public String getUserFramework() {
    return userFramework;
  }

  public void setUserFramework(String userFramework) {
    this.userFramework = userFramework;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.userName, user.userName) &&
        Objects.equals(this.userId, user.userId) &&
        Objects.equals(this.userLanguage, user.userLanguage) &&
        Objects.equals(this.userFramework, user.userFramework);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userName, userId, userLanguage, userFramework);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userLanguage: ").append(toIndentedString(userLanguage)).append("\n");
    sb.append("    userFramework: ").append(toIndentedString(userFramework)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
